### ISSUE TITLE
Optional automatic DependsOn generation

### ISSUE THREAD

**Issue by Vilo176** [canton7/PropertyChanged.SourceGenerator#36]
### Discussed in https://github.com/canton7/PropertyChanged.SourceGenerator/discussions/35

<div type='discussions-op-text'>

<sup>Originally posted by **Vilo176** November 23, 2022</sup>
Hi Antony,

Your SG is a very nice piece of code, thanks a lot for sharing.
Could you make Automatic DependsOn optional ?
I have some cases that I want to manage manually.

.editorconfig options will be nice.
Thanks 👍 </div>

**Comment by canton7** [comment]
This will be closed automatically when the release is cut

**Comment by Vilo176** [comment]
oups sorry
